version: '3.7'
services:
  app:
    build:
      dockerfile: ./.docker/app.dockerfile
      context: .
    entrypoint: dockerize -wait tcp://database_mysql:3306 -timeout 120s ./.docker/entrypoint.sh
    container_name: lkeeper_backend
    networks:
      - lkeeper_network
    ports:
      - '$PORT:3000'
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - './:/var/www/app'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - database_mysql
  database_mysql:
    image: mysql:5.7.29
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3306'
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: lkeeper
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lkeeper_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - lkeeper_network
    environment:
      ADMINER_DEFAULT_SERVER: database_mysql
    depends_on:
      - database_mysql
networks:
  lkeeper_network:
    driver: bridge
