version: "3.7"
services:
  app:
    build:
      dockerfile: ./.docker/app.dockerfile
      context: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: lkeeper_backend
    networks:
      - lkeeper_network
    ports:
      - "$PORT:3000"
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "./:/var/www/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  database_mysql:
    image: mysql:5.7.29
    command: --innodb-use-native-aio=0
    restart: always
    ports: 
      - "3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: lkeeper
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lkeeper_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - lkeeper_network
networks:
  lkeeper_network:
    driver: bridge
